fix: allow agent to run on CPU-only
Should fix 'AttributeError: 'NoneType' object has no attribute 'eglQueryString''. Required for running tests on GitHub actions CPU until we start using GPU runners